### ISSUE TITLE
Exception trying to run this code

### ISSUE THREAD

**Issue by scarton** [spring-guides/gs-yarn-basic#4]
I have Hadoop 2.6 and Yarn running as a two-node cluster.

I get this exception:

[2015-02-06 15:50:18.029] boot - 28104  INFO [main] --- AppmasterApplication: Starting AppmasterApplication on rscubuntu10 with PID 28104 (/tmp/hadoop-hduser/nm-local-dir/usercache/hduser/appcache/application_1423253562762_0002/filecache/10/gs-yarn-basic-appmaster-0.1.0.jar started by hduser in /tmp/hadoop-hduser/nm-local-dir/usercache/hduser/appcache/application_1423253562762_0002/container_1423253562762_0002_01_000001)
[2015-02-06 15:50:18.104] boot - 28104  INFO [main] --- AnnotationConfigApplicationContext: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@505b5629: startup date [Fri Feb 06 15:50:18 EST 2015]; root of context hierarchy
[2015-02-06 15:50:18.766] boot - 28104  INFO [Thread-2] --- AnnotationConfigApplicationContext: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@505b5629: startup date [Fri Feb 06 15:50:18 EST 2015]; root of context hierarchy
[2015-02-06 15:50:18.772] boot - 28104  WARN [Thread-2] --- AnnotationConfigApplicationContext: Exception thrown from ApplicationListener handling ContextClosedEvent
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@505b5629: startup date [Fri Feb 06 15:50:18 EST 2015]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:344)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)
[2015-02-06 15:50:18.792] boot - 28104  WARN [Thread-2] --- AnnotationConfigApplicationContext: Exception thrown from LifecycleProcessor on context close
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.context.annotation.AnnotationConfigApplicationContext@505b5629: startup date [Fri Feb 06 15:50:18 EST 2015]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:357)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:804)

**Comment by jvalkeal** [comment]
Because this sample as it is is expecting local single-node cluster you must have changed something in a configuration to point to your cluster.

How does your configuration look like and did you run this sample outside of your cluster or in one of the cluster nodes?

**Comment by jvalkeal** [comment]
One other things what may happen here is that yarn is killing those containers and you'd then get those weird errors.

```
spring:
    hadoop:
        fsUri: hdfs://node1:8020
        resourceManagerHost: node1
    yarn:
        appName: gs-yarn-basic
        applicationDir: /app/gs-yarn-basic/
        client:
            files:
              - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/gs-yarn-basic-container-0.1.0.jar"
              - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/gs-yarn-basic-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: gs-yarn-basic-appmaster-0.1.0.jar
            resource:
                memory: 512
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-basic-container-0.1.0.jar
            resource:
                memory: 512
```

This configuration worked for me when I run this sample externally against my hadoop cluster. I got same kind of error when I used default memory settings.

It's also worth to read something what I wrote in our XD on YARN docs for memory handling; https://github.com/spring-projects/spring-xd/wiki/Running-on-YARN
